### ISSUE TITLE
gridPULSE submission

### ISSUE THREAD

**Issue by afernandezcanosa** [GMLC-1-4-2/battery_interface#137]
@jmaguire1 @ORNLJD (CC. @Hayden-Reeve @hlngo) We need to submit the Battery-Equivalent model to the GMLC 1.2.3. gridPULSE repository. I was wondering if you have finished incorporating the latest updates on your code and merged into the master repo. Please, let me know if you are done so that I can submit the code.

Thanks!

**Comment by Hayden-Reeve** [comment]
@afernandezcanosa (@hlngo , @raselmahmud02 ),

I have made the repository public.  Please go ahead and link/contribute this to GridPulse.

Thanks
Hayden

**Comment by afernandezcanosa** [comment]
Thanks, @Hayden-Reeve 

The model is now available on gridPULSE under this link:
https://openlibrary.gridpulse.org/openlibrary/models/39b30aac

I need to reassign the admins and authors of the model as most of them disappear for an unknown reason. Also, as I opened the model with my ANL account, I cannot change the affiliation of the model.

I'll let you know all as soon as I update this.

Thanks.

**Comment by afernandezcanosa** [comment]
The authors and admins should have been updated now. Let me know if you find something wrong or if I have missed someone.
Thanks.
